server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=localhost user=postgres password=Ymriri dbname=testDb port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    dsn:
  redis:
    addr: 127.0.0.1:6379
    pass:
    db: 0 # 默认使用第0个
    read_timeout: 0.2s
    write_timeout: 0.2s
    expire: 86400      # 过期时间
