// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	MessageID   int64     `gorm:"column:message_id;primaryKey;comment:消息ID" json:"id"`             // 消息ID
	UIDSend     int64     `gorm:"column:uid_send;not null;comment:发送UID;发送用户" json:"from_user_id"` // 发送UID;发送用户
	UIDReceive  int64     `gorm:"column:uid_receive;not null;comment:接收用户;接收用户" json:"to_user_id"` // 接收用户;接收用户
	Content     string    `gorm:"column:content;not null;comment:内容;内容" json:"content"`            // 内容;内容
	CreatedBy   int64     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`        // 创建人
	CreatedTime time.Time `gorm:"column:created_time;not null;comment:创建时间" json:"created_tiime"`  // 创建时间 这里修改过，多了个i
	UpdatedBy   int64     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`        // 更新人
	UpdatedTime time.Time `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`   // 更新时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
