// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserVideo = "user_like_video"

// UserVideo mapped from table <user_like_video>
type UserVideo struct {
	LikeID      int64     `gorm:"column:like_id;primaryKey;comment:点赞ID;点赞ID" json:"like_id"`    // 点赞ID;点赞ID
	UserUID     int64     `gorm:"column:user_uid;not null;comment:用户UID;用户UID" json:"user_uid"`  // 用户UID;用户UID
	VideoID     int64     `gorm:"column:video_id;not null;comment:视频ID;视频ID" json:"video_id"`    // 视频ID;视频ID
	CreatedBy   int64     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`      // 创建人
	CreatedTime time.Time `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"` // 创建时间
	UpdatedBy   int64     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`      // 更新人
	UpdatedTime time.Time `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"` // 更新时间
	Delete      bool      `gorm:"column:delete;not null;comment:是否删除" json:"delete"`             // 是否删除
}

// TableName UserVideo's table name
func (*UserVideo) TableName() string {
	return TableNameUserVideo
}
