// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"feed/internal/biz/feed"
	"feed/internal/conf"
	"feed/internal/data"
	"feed/internal/server"
	"feed/internal/service/feed"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	feedServiceImpl := feed.NewFeedServiceImpl(dataData)
	feedService := service.NewFeedService(feedServiceImpl)
	grpcServer := server.NewGRPCServer(confServer, feedService, logger)
	httpServer := server.NewHTTPServer(confServer, feedService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
