// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/CyanPigeon/toktik/app/demo/internal/conf"
	"github.com/CyanPigeon/toktik/app/demo/internal/data"
	"github.com/CyanPigeon/toktik/app/demo/internal/server"
	"github.com/CyanPigeon/toktik/app/demo/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client, cleanup, err := data.NewDatabaseClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	repo := data.NewEntityRepoImpl(client, logger)
	greeterService := service.NewService(repo, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
