// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	VideoID      int64     `gorm:"column:video_id;primaryKey;comment:视频ID;视频主键" json:"id"`                  // 视频ID;视频主键
	UserUID      int64     `gorm:"column:user_uid;not null;comment:用户UID;用户UID" json:"user_uid"`            // 用户UID;用户UID
	Descripath   string    `gorm:"column:descripath;not null;comment:描述;描述" json:"descripath"`              // 描述;描述
	Title        string    `gorm:"column:title;not null;comment:标题;标题" json:"title"`                        // 标题;标题
	CoverPath    string    `gorm:"column:cover_path;not null;comment:封面地址;封面地址" json:"cover_url"`           // 封面地址;封面地址
	VideoPath    string    `gorm:"column:video_path;not null;comment:视频地址;视频地址" json:"play_url"`            // 视频地址;视频地址
	LikeCount    int64     `gorm:"column:like_count;not null;comment:点赞数;点赞数，默认0" json:"favorite_count"`    // 点赞数;点赞数，默认0
	CommentCount int64     `gorm:"column:comment_count;not null;comment:评论数;评论数量，默认0" json:"comment_count"` // 评论数;评论数量，默认0
	CreatedBy    int64     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                // 创建人
	CreatedTime  time.Time `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`           // 创建时间
	UpdatedBy    int64     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                // 更新人
	UpdatedTime  time.Time `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`           // 更新时间
	Delete       bool      `gorm:"column:delete;not null;comment:是否删除" json:"delete"`                       // 是否删除
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
