// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "tiktok_user"

// User mapped from table <tiktok_user>
type User struct {
	UID            int64     `gorm:"column:uid;primaryKey;comment:UID" json:"uid"`                                 // UID
	Username       string    `gorm:"column:username;not null;comment:用户昵称" json:"username"`                        // 用户昵称
	Password       string    `gorm:"column:password;not null;comment:加密后的密码" json:"password"`                      // 加密后的密码
	Avatar         string    `gorm:"column:avatar;not null;comment:头像;头像地址，有默认头像" json:"avatar"`                   // 头像;头像地址，有默认头像
	BackgroundImg  string    `gorm:"column:background_img;not null;comment:背景图片;有默认地址" json:"background_img"`      // 背景图片;有默认地址
	TotalFavorited int64     `gorm:"column:total_favorited;not null;comment:总获赞数;被点赞数" json:"total_favorited"`     // 总获赞数;被点赞数
	FollowCount    int64     `gorm:"column:follow_count;not null;comment:关注人数;关注数量，默认0" json:"follow_count"`       // 关注人数;关注数量，默认0
	FollowerCount  int64     `gorm:"column:follower_count;not null;comment:被关注人数;被关注数量，默认0" json:"follower_count"` // 被关注人数;被关注数量，默认0
	VideoCount     int64     `gorm:"column:video_count;not null;comment:作品数量;作品数量，默认0" json:"video_count"`         // 作品数量;作品数量，默认0
	FavoriteCount  int64     `gorm:"column:favorite_count;not null;comment:总点赞数;总点赞数" json:"favorite_count"`       // 总点赞数;总点赞数
	Signature      string    `gorm:"column:signature;not null;comment:个人简介;个人简介" json:"signature"`                 // 个人简介;个人简介
	CreatedBy      int64     `gorm:"column:created_by;not null;comment:创建人;创建人" json:"created_by"`                 // 创建人;创建人
	CreatedTime    time.Time `gorm:"column:created_time;not null;comment:创建时间;创建时间" json:"created_time"`           // 创建时间;创建时间
	UpdatedBy      int64     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                     // 更新人
	UpdatedTime    time.Time `gorm:"column:updated_time;not null;comment:更新时间;更新时间" json:"updated_time"`           // 更新时间;更新时间
	Delete         bool      `gorm:"column:delete;not null;comment:是否删除;是否删除" json:"delete"`                       // 是否删除;是否删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
