// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"message/internal/biz/message"
	"message/internal/conf"
	"message/internal/data"
	"message/internal/server"
	"message/internal/service/message"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	bizMessageServiceImpl := message.NewBizMessageService(dataData)
	messageActionService := service.NewMessageActionService(bizMessageServiceImpl)
	messageHistoryService := service.NewMessageHistoryService(bizMessageServiceImpl)
	grpcServer := server.NewGRPCServer(confServer, messageActionService, messageHistoryService, logger)
	httpServer := server.NewHTTPServer(confServer, messageActionService, messageHistoryService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
