// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	CommentID   int64     `gorm:"column:comment_id;primaryKey;comment:评论ID;评论id" json:"id"`      // 评论ID;评论id
	UserUID     int64     `gorm:"column:user_uid;not null;comment:用户UID;用户ID" json:"user_uid"`   // 用户UID;用户ID
	VideoID     int64     `gorm:"column:video_id;not null;comment:视频ID;视频ID" json:"video_id"`    // 视频ID;视频ID
	Content     string    `gorm:"column:content;not null;comment:评论;评论" json:"content"`          // 评论;评论
	CreatedBy   int64     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`      // 创建人
	CreatedTime time.Time `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"` // 创建时间
	UpdatedBy   int64     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`      // 更新人
	UpdatedTime time.Time `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"` // 更新时间
	Delete      bool      `gorm:"column:delete;not null;comment:是否删除" json:"delete"`             // 是否删除
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
