// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"relation/internal/biz"
	"relation/internal/conf"
	"relation/internal/data"
	"relation/internal/server"
	"relation/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	followRepo := data.NewFollowRepoImpl(dataData, logger)
	followUsecase := biz.NewFollowUsecase(followRepo, logger)
	followActionService := service.NewFollowActionService(followUsecase)
	followListService := service.NewFollowListService(followUsecase)
	followerListService := service.NewFollowerListService(followUsecase)
	friendListService := service.NewFriendListService(followUsecase)
	grpcServer := server.NewGRPCServer(confServer, followActionService, followListService, followerListService, friendListService, logger)
	httpServer := server.NewHTTPServer(confServer, followActionService, followListService, followerListService, friendListService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
